restaurant:
    path:     /
    defaults: { _controller: "MesdLunchBundle:Restaurant:index" }

restaurant_show:
    path:     /{id}/show
    defaults: { _controller: "MesdLunchBundle:Restaurant:show" }

restaurant_new:
    path:     /new
    defaults: { _controller: "MesdLunchBundle:Restaurant:new" }

restaurant_create:
    path:     /create
    defaults: { _controller: "MesdLunchBundle:Restaurant:create" }
    requirements: { _method: post }

restaurant_edit:
    path:     /{id}/edit
    defaults: { _controller: "MesdLunchBundle:Restaurant:edit" }

restaurant_update:
    path:     /{id}/update
    defaults: { _controller: "MesdLunchBundle:Restaurant:update" }
    requirements: { _method: post|put }

restaurant_delete:
    path:     /{id}/delete
    defaults: { _controller: "MesdLunchBundle:Restaurant:delete" }
    requirements: { _method: post|delete }
