<?php

namespace Mesd\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
	public function findRestaurant()
	{
		$count = $this->createQueryBuilder('r')
			->select('COUNT(r)')
			->getQuery()
			->getSingleScalarResult();
		return $this->createQueryBuilder('r')
			->setFirstResult(rand(0, $count - 1))
			->setMaxResults(1)
			->getQuery()
			->getSingleResult();
	}
}
