<?php

namespace Mesd\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
	public function findNoVoteRestaurant()
	{

		$qb = $this->createQueryBuilder('r');
		$qb->leftJoin('r.vote', 'v')
		->groupBy('r')
		->having($qb->expr()->eq(0, $qb->expr()->count('v.id')))
		;
		$qb = $this->createQueryBuilder('r');
		$qb->andWhere($qb->expr()->orX($qb->expr()->isNull('r.voteTotal'), $qb->expr()->eq(0,'r.voteTotal')))
		;
		// var_dump($qb->getQuery()->getDql());
		// print_r('<br><br>');
		// var_dump($qb->getQuery()->getSql());
		// die;

		$count = $this->createQueryBuilder('c')->select($qb->expr()->count('c.id'))->getQuery()->getSingleScalarResult();

		return $qb
			->setFirstResult(rand(0, $count - 1))
			->setMaxResults(1)
			->getQuery()
			->getSingleResult();
		
	}
}
