mesd_lunch_vote:
    resource: "@MesdLunchBundle/Resources/config/routing/vote.yml"
    prefix:   /vote

mesd_lunch_style:
    resource: "@MesdLunchBundle/Resources/config/routing/style.yml"
    prefix:   /style

mesd_lunch_restaurant:
    resource: "@MesdLunchBundle/Resources/config/routing/restaurant.yml"
    prefix:   /restaurant

mesd_lunch_homepage:
    path:     /hello/{name}
    defaults: { _controller: MesdLunchBundle:Default:index }

mesd_lunch_chosen:
    resource: "@MesdLunchBundle/Resources/config/routing/chosen.yml"
    prefix: /chosen

# mesd_lunch_voting:
#     resource: "@MesdLunchBundle/Resources/config/routing/voting.yml"
#     prefix:   /voting