Mesd\LunchBundle\Entity\Restaurant:
    type: entity
    table: null
    repositoryClass: Mesd\LunchBundle\Entity\RestaurantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        location:
            type: string
            length: 255
        hours:
            type: string
            length: '10'
        price:
            type: string
            length: '4'
        # type:
        #     type: string
        #     length: 255
        voteTotal:
            type: integer
            length: 2
            nullable: true
            column: vote_total

    manyToOne:
        style:
            targetEntity: Style 
            inversedBy: restaurant 
        type:
            targetEntity: Type 
            inversedBy: restaurant 

    oneToMany:
        vote:
            targetEntity: Vote
            mappedBy: restaurant





    lifecycleCallbacks: {  }
