Mesd\LunchBundle\Entity\Style:
    type: entity
    table: null
    repositoryClass: Mesd\LunchBundle\Entity\StyleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    oneToMany:
        restaurant:
            targetEntity: Restaurant 
            mappedBy: style 




    lifecycleCallbacks: {  }
